name: Ublisk
main: com.robinmc.ublisk.Main
version: 1.0.0
author: RobinMCDev
description: Ublisk plugin
depend: [NoteBlockAPI, ActionBarAPI, Citizens]

commands:
    menu:
        description: Opens the main menu
        usage: /<command>
    debug:
        description: Debugging command
        usage: </command> [args] [args]
    music:
        description: Opens a music selection menu
        usage: </command>
    help:
        description: Provides help
        usage: </command> [catagory]