name: Ublisk
main: com.robinmc.ublisk.Main
version: 1.0.0
author: RobinMCDev
description: Ublisk plugin
depend: [NoteBlockAPI, ActionBarAPI]

commands:
    menu:
        description: Opens the main menu
        usage: /<command>
    debug:
        description: Debugging command
        usage: </command> [args] [args]
    music:
        description: Opens a music selection menu
        usage: </command>
        aliases: [song, playsong, playmusic, songs]
    help:
        description: Provides help
        usage: </command> [catagory]
    credits:
        description: Credits
        usage: </command> [arguments]
    report:
        aliases: [reporthacker, reportplayer, rpplayer, rphacker, rp]
    suggest:
        aliases: [suggestfeature, newfeature, features, newfeatures, suggestfeatures, suggestion, suggestions]
    afk:
        aliases: [away, brb, awayfromkeyboard, back]