name: Ublisk
main: com.robinmc.ublisk.Main
version: 1.0.0
author: RobinMCDev
description: Ublisk plugin
depend: [NoteBlockAPI, ActionBarAPI]

commands:
    menu:
        description: Opens the Main menu
        usage: /<command>
    debug:
        description: Debugging command
        usage: </command> [args] [args]