name: Ublisk
main: com.robinmc.ublisk.Main
version: 6.9
author: RobinMCDev
description: Ublisk plugin
softdepend: [NoteBlockAPI, BossBarAPI, Votifier]

commands:
    menu:
        description: Opens the main menu
        usage: /<command>
    debug:
        description: Debugging command
        usage: </command> [args] [args]
        aliases: [ublisk, u]
    help:
        description: Provides help
        usage: </command> [catagory]
        aliases: [support]
    credits:
        description: Credits
        usage: </command> [arguments]
    report:
        aliases: [reporthacker, reportplayer, rpplayer, rphacker, rp]
    contact:
        aliases: [suggestfeature, newfeature, features, feature, newfeatures, suggestfeatures, suggestion, suggestions, bug, bugs, reportbug, bugreport, admincontact, ownercontant, ask, apply, operatorhelp, ophelp, helpop, askop, askoperator, askmod, askadmin, askowner]
    afk:
        aliases: [away, brb, awayfromkeyboard, back]
    class:
        usage: </command>
    friends:
        aliases: [friend, f, friendlist, friendslist]
    mute:
        aliases: [holdyourbekpls,stfu]
    msg:
        aliases: [w, write, tell, pm, mail, email, m, msg, message, privatem, pmessage,t]
    builder:
        usage: </command>
    guild:
        aliases: [guilds, g]
    pack:
        aliases: [resources, resource, resourcepack, texture, textures, texturepack]
    voterestart:
        aliases: [voteforrestart, restart]
        