name: Ublisk
main: com.robinmc.ublisk.Main
version: 6.9
author: RobinMCDev
description: Ublisk plugin
depend: [NoteBlockAPI, ActionBarAPI, NPCLib, ResourcePackApi, BossBarAPI, ItemNBTAPI, PermissionsEx]

commands:
    menu:
        description: Opens the main menu
        usage: /<command>
    debug:
        description: Debugging command
        usage: </command> [args] [args]
    help:
        description: Provides help
        usage: </command> [catagory]
        aliases: [support]
    credits:
        description: Credits
        usage: </command> [arguments]
    report:
        aliases: [reporthacker, reportplayer, rpplayer, rphacker, rp]
    suggest:
        aliases: [suggestfeature, newfeature, features, newfeatures, suggestfeatures, suggestion, suggestions]
    afk:
        aliases: [away, brb, awayfromkeyboard, back]
    class:
        usage: </command>
    friends:
        aliases: [friend, f, friendlist, friendslist]
    mute:
        aliases: [holdyourbekpls]
    msg:
        aliases: [w,write,tell,pm,mail,m,msg,message,privatem,pmessage,t]