name: Ublisk
main: com.robinmc.ublisk.Main
version: 1.0.0
author: RobinMCDev
description: Ublisk plugin
depend: [NoteBlockAPI, Vault]

commands:
    menu:
        description: Open the Main menu!
        usage: /<command>